# Generated by Django 5.2.7 on 2025-11-03 06:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
