# Generated by Django 5.2.7 on 2025-11-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'default_permissions': ('add', 'change')},
        ),
    ]
