# Generated by Django 5.2.7 on 2025-11-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permission', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_view_list', 'Can publish posts'), ('can_search_list', 'Can view post statistics')]},
        ),
    ]
