# Generated by Django 5.2.7 on 2025-11-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permission', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('filter_student', 'Can view student'), ('search_student', 'Can search student')]},
        ),
    ]
