# Generated by Django 5.2.7 on 2025-10-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stuff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Staff',
        ),
    ]
