# Generated by Django 5.2.7 on 2025-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_stuff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='restaurant',
            field=models.ManyToManyField(related_name='stuffs', to='core.restaurant'),
        ),
    ]
