# Generated by Django 5.2.7 on 2025-10-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=59),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(models.OrderBy(models.F('name'), descending=True), models.OrderBy(models.F('roll')), name='name_desc_roll_idx'),
        ),
    ]
