# Generated by Django 5.2.7 on 2025-10-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_student_roll'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_db',
        ),
    ]
