# Generated by Django 5.2.7 on 2025-10-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll']},
        ),
    ]
