# Generated by Django 5.2.7 on 2025-10-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-roll']},
        ),
    ]
