# Generated by Django 5.2.7 on 2025-10-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_student_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'roll')},
        ),
    ]
