# Generated by Django 6.0.1 on 2026-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_pro_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
