# Generated by Django 5.2.7 on 2025-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=20)),
                ('lname', models.TextField(max_length=20)),
                ('name', models.TextField(editable=False)),
                ('roll', models.PositiveIntegerField(editable=False, unique=True)),
                ('birth', models.DateTimeField()),
                ('age', models.PositiveIntegerField(editable=False)),
                ('batch', models.PositiveSmallIntegerField()),
                ('department', models.TextField(choices=[('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BBA', 'Bachelor of Business Administration'), ('BCom', 'Bachelor of Commerce'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy')])),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('medium', models.TextField(choices=[('Bn', 'Bangla'), ('Eng', 'English')])),
            ],
        ),
    ]
