# Generated by Django 5.2.7 on 2025-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(),
        ),
    ]
