# Generated by Django 5.2.7 on 2025-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0002_alter_student_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
    ]
