# Generated by Django 5.2.7 on 2025-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0003_alter_student_fname_alter_student_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(editable=False),
        ),
    ]
