# Generated by Django 5.2.7 on 2025-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0004_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
    ]
