# Generated by Django 5.2.7 on 2025-10-29 17:20

import tempt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0005_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.PositiveSmallIntegerField(validators=[tempt.models.batch_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('BSc', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BBA', 'Bachelor of Business Administration'), ('BCom', 'Bachelor of Commerce'), ('MSc', 'Master of Science'), ('MA', 'Master of Arts'), ('MBA', 'Master of Business Administration'), ('PhD', 'Doctor of Philosophy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='medium',
            field=models.CharField(choices=[('Bn', 'Bangla'), ('Eng', 'English')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(editable=False, max_length=101),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
