# Generated by Django 5.2.7 on 2025-10-29 17:35

import tempt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0006_alter_student_batch_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(validators=[tempt.models.validate_birth]),
        ),
    ]
