# Generated by Django 5.2.7 on 2025-10-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempt', '0007_alter_student_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
