FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential libpq-dev curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install gunicorn whitenoise

COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

EXPOSE 8000

# Run Gunicorn
CMD ["gunicorn", "modelLogDoc.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
